theme = "mehefin"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 85
show_marks = "visible"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "uptime"
interval = 60

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "sound"

[[block]]
block = "music"
player = "cmus"
max_width = 15
buttons = ["play", "prev", "next"]

[[block]]
block = "custom"
command = "curl -Ss 'https://wttr.in/your_city?format=1' | awk '{print $2}'"
interval = 1800

[[block]]
block = "time"
interval = 1
format = "%I:%M:%S %a %d %b %G"
