idle_bg = "#14101e"
idle_fg = "#e89494"
info_bg = "#14101e"
info_fg = "#e89494"
good_bg = "#14101e"
good_fg = "#b77859"
warning_bg = "#14101e"
warning_fg = "#b77859"
critical_bg = "#14101e"
critical_fg = "#b77859"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"
